"""Shared contracts between v2 research, portfolio, and execution modules."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Literal

SignalType = Literal["BUY", "SELL", "HOLD", "DRIFT_ALERT"]
OrderSide = Literal["BUY", "SELL"]
ModelDirection = Literal["BUY", "SELL", "HOLD"]


@dataclass(frozen=True)
class MarketRiskSnapshot:
    """Portfolio-wide market context used by short-side safety guards."""

    lookback_hours: int
    symbols_evaluated: int
    down_ratio: float
    median_return: float
    btc_return: float | None = None
    broad_selloff: bool = False
    down_ratio_threshold: float = 0.70
    median_return_threshold: float = -0.015
    btc_return_threshold: float = -0.020
    strong_short_confidence: float = 0.75
    short_net_cap_frac: float = 0.15

    def __post_init__(self) -> None:
        if self.lookback_hours <= 0:
            raise ValueError("lookback_hours must be positive")
        if self.symbols_evaluated < 0:
            raise ValueError("symbols_evaluated cannot be negative")
        if not 0.0 <= self.down_ratio <= 1.0:
            raise ValueError("down_ratio must be within [0, 1]")
        if not 0.0 <= self.down_ratio_threshold <= 1.0:
            raise ValueError("down_ratio_threshold must be within [0, 1]")
        if not 0.0 <= self.strong_short_confidence <= 1.0:
            raise ValueError("strong_short_confidence must be within [0, 1]")
        if not 0.0 <= self.short_net_cap_frac <= 1.0:
            raise ValueError("short_net_cap_frac must be within [0, 1]")

    def as_dict(self) -> dict[str, float | int | bool | None]:
        return {
            "lookback_hours": self.lookback_hours,
            "symbols_evaluated": self.symbols_evaluated,
            "down_ratio": self.down_ratio,
            "median_return": self.median_return,
            "btc_return": self.btc_return,
            "broad_selloff": self.broad_selloff,
            "down_ratio_threshold": self.down_ratio_threshold,
            "median_return_threshold": self.median_return_threshold,
            "btc_return_threshold": self.btc_return_threshold,
            "strong_short_confidence": self.strong_short_confidence,
            "short_net_cap_frac": self.short_net_cap_frac,
        }


@dataclass(frozen=True)
class ModelSourceDetails:
    """Source-level model probabilities used for agreement-aware routing."""

    lgbm_probability: float | None
    chronos_probability: float | None
    final_probability: float
    lgbm_direction: ModelDirection | None
    chronos_direction: ModelDirection | None
    agreement: bool | None
    chronos_enabled: bool = False

    def __post_init__(self) -> None:
        for name, value in (
            ("lgbm_probability", self.lgbm_probability),
            ("chronos_probability", self.chronos_probability),
            ("final_probability", self.final_probability),
        ):
            if value is not None and not 0.0 <= value <= 1.0:
                raise ValueError(f"{name} must be within [0, 1]")
        valid = {"BUY", "SELL", "HOLD"}
        if self.lgbm_direction is not None and self.lgbm_direction not in valid:
            raise ValueError("lgbm_direction must be BUY, SELL, or HOLD")
        if self.chronos_direction is not None and self.chronos_direction not in valid:
            raise ValueError("chronos_direction must be BUY, SELL, or HOLD")

    def as_dict(self) -> dict[str, float | str | bool | None]:
        return {
            "lgbm_probability": self.lgbm_probability,
            "chronos_probability": self.chronos_probability,
            "final_probability": self.final_probability,
            "lgbm_direction": self.lgbm_direction,
            "chronos_direction": self.chronos_direction,
            "agreement": self.agreement,
            "chronos_enabled": self.chronos_enabled,
        }


@dataclass(frozen=True)
class StrategySignal:
    """A normalized strategy signal generated by the model layer."""

    symbol: str
    timeframe: str
    horizon_bars: int
    signal: SignalType
    confidence: float
    uncertainty: float | None = None
    reason: str = ""
    regime: int | None = None
    session_hour_utc: int | None = None
    momentum_bias: float | None = None
    atr_pct: float | None = None
    symbol_hit_rate: float | None = None
    event_gate_mult: float | None = None
    model_agreement: float | None = None
    estimated_cost_bps: float | None = None
    pairwise_correlations: dict[str, float] | None = None
    portfolio_weight: float | None = None
    market_risk: MarketRiskSnapshot | None = None
    model_sources: ModelSourceDetails | None = None

    def __post_init__(self) -> None:
        if not self.symbol:
            raise ValueError("Signal symbol cannot be empty")
        if not self.timeframe:
            raise ValueError("Signal timeframe cannot be empty")
        if self.horizon_bars <= 0:
            raise ValueError("horizon_bars must be positive")
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError("Signal confidence must be within [0, 1]")
        if self.uncertainty is not None and not 0.0 <= self.uncertainty <= 1.0:
            raise ValueError("Signal uncertainty must be within [0, 1]")
        if self.regime is not None and self.regime not in {1, 2, 3, 4}:
            raise ValueError("regime must be one of 1, 2, 3, or 4")
        if self.session_hour_utc is not None and not 0 <= self.session_hour_utc <= 23:
            raise ValueError("session_hour_utc must be within [0, 23]")
        if self.momentum_bias is not None and not -1.0 <= self.momentum_bias <= 1.0:
            raise ValueError("momentum_bias must be within [-1, 1]")
        if self.atr_pct is not None and self.atr_pct < 0.0:
            raise ValueError("atr_pct must be >= 0")
        if self.symbol_hit_rate is not None and not 0.0 <= self.symbol_hit_rate <= 1.0:
            raise ValueError("symbol_hit_rate must be within [0, 1]")
        if self.event_gate_mult is not None and not 0.0 <= self.event_gate_mult <= 1.0:
            raise ValueError("event_gate_mult must be within [0, 1]")
        if self.model_agreement is not None and not 0.0 <= self.model_agreement <= 1.0:
            raise ValueError("model_agreement must be within [0, 1]")
        if self.estimated_cost_bps is not None and self.estimated_cost_bps < 0.0:
            raise ValueError("estimated_cost_bps must be >= 0")

    @property
    def actionable(self) -> bool:
        return self.signal in {"BUY", "SELL"}


@dataclass(frozen=True)
class ExecutionIntent:
    """Portfolio-aware execution target derived from one or more signals."""

    symbol: str
    signal: StrategySignal
    target_notional_usd: float
    risk_budget_frac: float
    reduce_only: bool = False

    def __post_init__(self) -> None:
        if not self.symbol:
            raise ValueError("Intent symbol cannot be empty")
        if not 0.0 <= self.risk_budget_frac <= 1.0:
            raise ValueError("risk_budget_frac must be within [0, 1]")


@dataclass(frozen=True)
class OrderPlan:
    """Venue-ready order instructions with idempotency support."""

    symbol: str
    side: OrderSide
    quantity: float
    reduce_only: bool = False
    client_order_id: str | None = None

    def __post_init__(self) -> None:
        if not self.symbol:
            raise ValueError("Order symbol cannot be empty")
        if self.quantity <= 0.0:
            raise ValueError("Order quantity must be positive")


@dataclass(frozen=True)
class RiskSnapshot:
    """Instantaneous risk state for a portfolio."""

    gross_exposure_frac: float
    net_exposure_frac: float
    max_drawdown_frac: float
    risk_budget_used_frac: float

    def __post_init__(self) -> None:
        if self.gross_exposure_frac < 0.0:
            raise ValueError("gross_exposure_frac cannot be negative")
        if abs(self.net_exposure_frac) > self.gross_exposure_frac + 1e-12:
            raise ValueError("|net_exposure_frac| cannot exceed gross_exposure_frac")
        if not 0.0 <= self.max_drawdown_frac <= 1.0:
            raise ValueError("max_drawdown_frac must be within [0, 1]")
        if self.risk_budget_used_frac < 0.0:
            raise ValueError("risk_budget_used_frac cannot be negative")


@dataclass(frozen=True)
class PortfolioSnapshot:
    """Compact portfolio state returned to control-plane integrations."""

    timestamp: datetime
    equity_usd: float
    open_positions: dict[str, float] = field(default_factory=dict)
    symbol_pnl_usd: dict[str, float] = field(default_factory=dict)
    symbol_notional_usd: dict[str, float] = field(default_factory=dict)
    risk: RiskSnapshot | None = None

    def __post_init__(self) -> None:
        if self.equity_usd <= 0.0:
            raise ValueError("equity_usd must be positive")

    @property
    def symbol_count(self) -> int:
        return len(self.open_positions)
