"""Shared contracts between v2 research, portfolio, and execution modules."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Literal

SignalType = Literal["BUY", "SELL", "HOLD", "DRIFT_ALERT"]
OrderSide = Literal["BUY", "SELL"]


@dataclass(frozen=True)
class StrategySignal:
    """A normalized strategy signal generated by the model layer."""

    symbol: str
    timeframe: str
    horizon_bars: int
    signal: SignalType
    confidence: float
    uncertainty: float | None = None
    reason: str = ""

    def __post_init__(self) -> None:
        if not self.symbol:
            raise ValueError("Signal symbol cannot be empty")
        if not self.timeframe:
            raise ValueError("Signal timeframe cannot be empty")
        if self.horizon_bars <= 0:
            raise ValueError("horizon_bars must be positive")
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError("Signal confidence must be within [0, 1]")
        if self.uncertainty is not None and not 0.0 <= self.uncertainty <= 1.0:
            raise ValueError("Signal uncertainty must be within [0, 1]")

    @property
    def actionable(self) -> bool:
        return self.signal in {"BUY", "SELL"}


@dataclass(frozen=True)
class ExecutionIntent:
    """Portfolio-aware execution target derived from one or more signals."""

    symbol: str
    signal: StrategySignal
    target_notional_usd: float
    risk_budget_frac: float
    reduce_only: bool = False

    def __post_init__(self) -> None:
        if not self.symbol:
            raise ValueError("Intent symbol cannot be empty")
        if not 0.0 <= self.risk_budget_frac <= 1.0:
            raise ValueError("risk_budget_frac must be within [0, 1]")


@dataclass(frozen=True)
class OrderPlan:
    """Venue-ready order instructions with idempotency support."""

    symbol: str
    side: OrderSide
    quantity: float
    reduce_only: bool = False
    client_order_id: str | None = None

    def __post_init__(self) -> None:
        if not self.symbol:
            raise ValueError("Order symbol cannot be empty")
        if self.quantity <= 0.0:
            raise ValueError("Order quantity must be positive")


@dataclass(frozen=True)
class RiskSnapshot:
    """Instantaneous risk state for a portfolio."""

    gross_exposure_frac: float
    net_exposure_frac: float
    max_drawdown_frac: float
    risk_budget_used_frac: float

    def __post_init__(self) -> None:
        if self.gross_exposure_frac < 0.0:
            raise ValueError("gross_exposure_frac cannot be negative")
        if abs(self.net_exposure_frac) > self.gross_exposure_frac + 1e-12:
            raise ValueError("|net_exposure_frac| cannot exceed gross_exposure_frac")
        if not 0.0 <= self.max_drawdown_frac <= 1.0:
            raise ValueError("max_drawdown_frac must be within [0, 1]")
        if not 0.0 <= self.risk_budget_used_frac <= 1.0:
            raise ValueError("risk_budget_used_frac must be within [0, 1]")


@dataclass(frozen=True)
class PortfolioSnapshot:
    """Compact portfolio state returned to control-plane integrations."""

    timestamp: datetime
    equity_usd: float
    open_positions: dict[str, float] = field(default_factory=dict)
    symbol_pnl_usd: dict[str, float] = field(default_factory=dict)
    risk: RiskSnapshot | None = None

    def __post_init__(self) -> None:
        if self.equity_usd <= 0.0:
            raise ValueError("equity_usd must be positive")

    @property
    def symbol_count(self) -> int:
        return len(self.open_positions)
